### ISSUE TITLE
Remain backwards compatible with `X-OCTOBER-REQUEST-HANDLER`

### ISSUE THREAD

**Issue by tobias-kuendig** [wintercms/winter#189]
We just got this PR:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/764/files

I feel like it would be a better solution to keep Winter backwards compatible (look for the "old" and "new" headers) instead of updating all of the plugins that access this header directly.

What are your thoughts on that?

**Comment by bennothommo** [comment]
@tobias-kuendig yeah, this has been brought up in the Discord. The issue isn't your plugin, it's that we *send* an `X-WINTER-REQUEST-HANDLER` instead of an `X-OCTOBER-REQUEST-HANDLER`.

We can send both, I suppose, but we're trying to avoid the association and infringing on October's trademarks. The intention of those headers were to be "system" headers that weren't used directly by functionality.

I'll bring it up with the team and get back to you. I'll also suggest something with that PR on the Mall plugin to at least remove one of the backwards-incompatibility issues.
