### ISSUE TITLE
 php artisan winter:version error on macOs In SourceManifest.php line 112:

### ISSUE THREAD

**Issue by remko-key** [wintercms/winter#267]
Hey WinterCms,

I'm using **WinterCMS 1.1.3** on a Mac running php 7.3.27. When I run **php artisan winter:version** which is part of composer post-update-cmd I'm getting an error:

```
*** Detecting Winter CMS build...

In SourceManifest.php line 112:
                                                                                     
file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:     
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

```

is it possible to replace the **file_get_contents** function with  **Winter\Storm\Network\Http::get** method  in SourceManifest.php line 112 and 151

```
use Winter\Storm\Network\Http;
$source = Http::get($this->source);  on line 112 and 151 

``` 
When I change this in the code winter:version works again on my Mac.

**Comment by bennothommo** [comment]
Thanks @meinmotion - that's a good fix.

Fixed by https://github.com/wintercms/winter/commit/e7c43c5aa16d26cfa5b996b2ce62cdeb654dba26.

**Comment by remko-key** [comment]
Your welcome and keep up the good work with this great CMS

**Comment by ajaxStardust** [comment]
> is it possible to replace the **file_get_contents** function with **Winter\Storm\Network\Http::get** method in SourceManifest.php line 112 and 151
> 
> ```
> use Winter\Storm\Network\Http;
> $source = Http::get($this->source);  on line 112 and 151 
> ```
> 
> When I change this in the code winter:version works again on my Mac.

What might be the filesystem path to the file which contains this code?

in file ```vendor/winter/storm/src/Network/Http.php```
namespace would be this file. but, i don't understand what you're doing at line 112/151. perhaps the code has changed since this was addressed?

thank you!

```
<?php namespace Winter\Storm\Network;

use Winter\Storm\Exception\ApplicationException;
use Winter\Storm\Support\Str;

/**
 * HTTP Network Access
 *
 * Used as a cURL wrapper for the HTTP protocol.
 *
 * Usage:
 *
 *   Http::get('https://wintercms.com');
 *   Http::post('...');
 *   Http::delete('...');
 *   Http::patch('...');
 *   Http::put('...');
 *   Http::options('...');
 *   Http::head('...');
 *
 *   $result = Http::post('https://wintercms.com');
 *   echo $result;                          // Outputs: <html><head><title>...
 *   echo $result->code;                    // Outputs: 200
 *   echo $result->headers['Content-Type']; // Outputs: text/html; charset=UTF-8
 *
```

just playing around with it so far at http://vps111.heliohost.us - if you like that dirtree thing [check the "Theme" page there?]. i use visuals like that to get my head around stuff at first. sometimes. i was going to put that on a bitbucket thing [or here], but... not im encountering this issue... 

FTR. brain damaged here, so i sometimes don't make sense. i'm not drunk or high. haha. well. never drunk, and not presently! lol. 

so, that code tells me this about the class, 
```
 * Usage:
 *
 *   Http::get('https://wintercms.com');
```
but i'm not putting dua & lipa together. 
thank yoU!

**Comment by bennothommo** [comment]
@ajaxStardust I'm not sure what you're asking here. Are you asking for assistance in working out what the `Http` class does?
