### ISSUE TITLE
Mail template translations not working

### ISSUE THREAD

**Issue by bennothommo** [wintercms/winter#329]
### Discussed in https://github.com/wintercms/winter/discussions/327

<div type='discussions-op-text'>

<sup>Originally posted by **AIC-BV** October  5, 2021</sup>
Hello!

I am trying to translate my Mail Templates, which is working by adding the following code in my boot() function:
>         \System\Models\MailTemplate::extend(function ($model) {
>             $model->addDynamicProperty('translatable', []);
>             $model->translatable = array_merge($model->translatable, ['subject@create', 'subject@update', 'description', 'content_html', 'content_text']);
>             $model->extendClassWith('Winter\Translate\Behaviors\TranslatableModel');
>         });

Just one small issue, even though the mail is translatable in the backend at `settings -> mail templates`, the mail always sends in the default language and doesn't listen to the activeLocale (I'm using Winter.Translate).

Any ideas how to solve this problem so that the mail sends in the correct language?
I am sending the mail with a queue:

        Mail::queue(aic.contact::mail.contact, $data, function($message) use (&$data) {
            // get the theme variables
            $sender = $theme->mail_email;
            $senderName = $theme->mail_name;

            // receiver
            $email = $data['email'];
            $name = $data['fname'] . ' ' . $data['lname'];

            // set properties
            $message->from($sender, $senderName);
            $message->to($email, $name);
        });

Edit:
The suggested solution from daftspunk, which was already implemented in WinterCMS, does not seem to solve my issue: https://github.com/wintercms/storm/pull/50

Edit 2:
Maybe related to this issue;
I have this field in 'fields.yaml' for my theme:

```
  street:
        tab: Contact
        label: Straat
        type: text
        span: left
        translatable: true
```

When printing my theme variable: `{{ this.theme.street }}`; it's always in the default language and my translated value is ignored. I'm absolutely sure this used to work a few days ago. Maybe I broke something? I didn't touch any plugins and commenting my plugin code doesn't affect this issue, and the translations are visible in the database in `winter_translate_attributes`</div>

**Comment by mjauvin** [comment]
@bennothommo I know for a fact this used to work since I wrote this and it has been tested extensively... I'm browsing the code to find where "_current_locale" is retrieved and can't find it anywhere... so it's saving the locale when the mail gets queued, but does not retrieve it anymore before actually sending the mail... so something was changed that nuked this code.

**Comment by mjauvin** [comment]
@bennothommo I was looking in the wrong place... the code I was referring to is in `Winter.Translate`. Look for `findLocalizedMailViewContent()`

It's not using translatable fields, though, it's using localized content/view files...

**Comment by mjauvin** [comment]
Hmmm, just found code where the App locale was restored was removed at some point, not sure why...

See [cc1c88a6062a9686aa70b40b67c89ea8b0c5dc5f](https://github.com/wintercms/storm/commit/cc1c88a6062a9686aa70b40b67c89ea8b0c5dc5f)

I'm thinking we need to apply this patch:
```diff
diff --git a/src/Mail/Mailable.php b/src/Mail/Mailable.php
index 78722102..293679af 100644
--- a/src/Mail/Mailable.php
+++ b/src/Mail/Mailable.php
@@ -32,6 +32,11 @@ public function buildViewData()
     {
         $data = $this->viewData;
 
+        // retrieve saved locale
+        if (isset($data['_current_locale'])) {
+            App::setLocale($data['_current_locale']);
+        }
+           
         foreach ($data as $param => $value) {
             $data[$param] = $this->getRestoredPropertyValue($value);
         }
```

Can you try this @bennothommo and see if that resolve your issue ?

**Comment by mjauvin** [comment]
@bennothommo I commited three changes in Winter-Translate plugin that resolve the issue:

- first one fixes the context issue for fields in `$translatable[]` array (you don't nee to provide the context anymore)
- second fix Sets the front-end translator locale from the saved queued mail data so that the model can use the proper locale when accessed in `\system\Classes\MailManager`.
- last one makes the MailTemplate translatable by default in translate plugin.

Let me know how it goes.

**Comment by bennothommo** [comment]
@mjauvin nice one! I can certainly give it a test, maybe @AIC-BV will be able to as well, as the original reporter?

**Comment by mjauvin** [comment]
Ahah, didn't even realize you were not the original poster... It did seem weird you would require translation, though... :)

**Comment by bennothommo** [comment]
Ironically, my new job might require translations down the track, so I may be more involved soon :)

**Comment by AIC-BV** [comment]
Unbelievable that some companies/people still don't want/need translations nowadays! To me it is fundamental to everything I develop.
I will test it later this week/beginning next week!

**Comment by AIC-BV** [comment]
I am stuck on this error, I don't have the latest version due to several changes I made with @mjauvin.
I will have to check all the changes and see wether they are implemented or not before I can get the latest version of translate & sitemap
![image](https://github.com/wintercms/winter/assets/89913092/1a7ad24f-a7cd-45fb-9e19-50d947c4bcc3)

**Comment by AIC-BV** [comment]
Translatable mails work with latest branch 🙂 
![image](https://github.com/wintercms/winter/assets/89913092/e0d5a2b4-d59d-4191-a0fd-d3ea113d06ef)

**Comment by mjauvin** [comment]
Fixed by https://github.com/wintercms/wn-translate-plugin/pull/63
