### ISSUE TITLE
Plugin tests can't run in non-debug mode

### ISSUE THREAD

**Issue by lex0r** [wintercms/winter#425]
### Winter CMS Build

dev-develop

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

When running plugin tests (those inherited from PluginTestCase) with APP_DEBUG set to false I get an error saying:

Error: Call to undefined method Illuminate\Support\Facades\Cache::remember()

This is probably because earlier during the bootstrap process a Cache facade fake was configured to be used as Cache, and /winter/storm/src/Parse/Yaml.php fails to call "remember" on it.

### Steps to replicate

1. Make sure APP_DEBUG=false
2. Install Winter.Translate
3. Change to plugins/winter/translate directory
4. Run `../../../vendor/bin/phpunit`

Expected result: the tests pass
Actual result: multiple errors Error: Call to undefined method Illuminate\Support\Facades\Cache::remember()

**Comment by LukeTowers** [comment]
Couple issues, first: PHP 8.1 isn't supported on the develop branch, only dev-wip/1.2 which is our WIP branch for Laravel 9 support.

Second: The issue that triggers that error was fixed in https://github.com/wintercms/winter/commit/9314a4442e2695b3665e2fa2e0cf1788809e02d8, are you sure you have the latest dev-develop?

**Comment by lex0r** [comment]
@LukeTowers  indeed, the fix addresses the issue, thank you for pointing out.
