### ISSUE TITLE
Cache::remember not working as expected

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/winter#550]
### Winter CMS Build

1.1

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Sitemap, Winter.Pages, Winter.TinyPNG, Winter.Translate, Winter.Redirects, Aic.Globals, Aic.ExtendWinterPages, Aic.Blog, Aic.Team, Aic.Account, Aic.Contact, Aic.Invoice, Aic.Discount, Aic.Aftersales, Aic.Reviews, Aic.Faq, StudioBosco.BackendNotifications, StudioBosco.BackendComments, ...

### Issue description

Cache runs many times instead of once per month. Log gets spammed with the message "monthly_maintenance"

### Steps to replicate

Just try Cache in the boot() function in your Plugin.php file
```
use Log;
use Cache;
use Carbon\Carbon;
...
Cache::remember('monthly_maintenance', Carbon::now()->addMonths(1), function () {
    Log::info('monthly_maintenance');
})
```
Click the refresh button (or refresh your page CTRL+R / CMD+R) and it will keep on adding the log with more than one record at once
![image](https://user-images.githubusercontent.com/89913092/166884696-e7286037-92b7-41c8-b284-9412421df87c.png)

**Comment by bennothommo** [comment]
@AIC-BV if you don't return a value when using `Cache::remember`, then it won't cache - that's why it continues to fire off the log. You must return a value in the callback in order for the cache to populate and remember.

**Comment by AIC-BV** [comment]
> @AIC-BV if you don't return a value when using `Cache::remember`, then it won't cache - that's why it continues to fire off the log. You must return a value in the callback in order for the cache to populate and remember.

Ow 🤦‍♂️ Sorry!

**Comment by AIC-BV** [comment]
@bennothommo Would it be best to create a `Cache::remember` for each action I want it to do, or create a single `Cache::remember` running all actions and returning an empty string?

**Comment by bennothommo** [comment]
@AIC-BV I'd say if you're intending to have something that runs monthly, you might be better using [Task Scheduling](https://wintercms.com/docs/plugin/scheduling) instead of the `Cache::remember()` call. You can set up a task to run multiple actions, or you could split the actions into individual scheduled tasks - it's entirely up to you :)

**Comment by AIC-BV** [comment]
The Task Schedueler is
- much harder to set up
- doesn't work locally out of the box (so I can't test it in advance)
- can basically do the same thing as I want with Cache?
I think i'll stick with Cache to make my life easier 😄

**Comment by LukeTowers** [comment]
@AIC-BV the downsides of using cache instead of scheduled tasks are the following:
- You have to trigger the call to the cache remember method at least once a month manually
- Unless you explicitly set something up you won't know if your scheduled task has failed.

It's easy to setup scheduling locally and in production, see https://wintercms.com/docs/setup/installation#crontab-setup. You can also use a service like OhDear to keep track of whether or not your scheduled tasks are completing successfully on an ongoing basis; and you don't have to manually trigger it at all.

**Comment by AIC-BV** [comment]
@LukeTowers What do you mean 'manually'?
Do you mean the backend needs to be manually opened for the code to be able to run?
Our backend is used almost daily so that shouldn't be a problem for my case, but I understand your argument!
```
public function boot()
{
    Cache::remember('monthly_maintenance', Carbon::now()->addMonths(1), function () {
        Log::info('Monthly Maintenance');
        return '';
    }
}
```

**Comment by LukeTowers** [comment]
That's correct @AIC-BV

**Comment by LukeTowers** [comment]
@AIC-BV also note that logging into the backend clears the cache in some cases AFAIK, so every time the cache is cleared your code will run again.

**Comment by AIC-BV** [comment]
I see. Cronjob would be more reliable and performant
