### ISSUE TITLE
Infinite loop when calling getOriginal within accessor. 

### ISSUE THREAD

**Issue by mjauvin** [wintercms/winter#566]
### Winter CMS Build

Other (please specify below)

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

In Laravel 7+, when getOriginal() is called from within an attribute "get mutator" for the same attribute, an infinite loop is created.

ref. https://laravel.com/docs/7.x/upgrade#factory-types

### Steps to replicate

In your model, create an attribute accessor (get mutator in laravel's term):

```php
public function getNameAttribute($value)
{
    return $this->getOriginal('name');
}      
```

### Workaround

use `getRawOriginal()` method instead.

**Comment by bennothommo** [comment]
Personally, I think this may have to be fixed at the plugin level, as it's only the edge cases tripping up on this, like with the example above.

We'd be better to keep parity with Laravel on this or we risk functionality breaking elsewhere.

**Comment by LukeTowers** [comment]
The vast majority of uses of getOriginal() in Winter & October plugins that I've seen in the wild tend to use getOriginal() in afterSave for change tracking rather than the method described above. Additionally, I'm not sure why anyone would use the provided example instead of just treating the passed argument as the original value.

Closing as an edge case that shouldn't have really worked in the first place.
