### ISSUE TITLE
Error Iconpicker

### ISSUE THREAD

**Issue by WebVPF** [wintercms/winter#826]
### Winter CMS Build

dev-develop

### PHP Version

8.0

### Database engine

MySQL/MariaDB

### Plugins installed

wn-test-plugin

### Issue description

The [Icon Picker](https://wintercms.com/docs/backend/forms#widget-iconpicker) widget is not working.

> Uncaught TypeError: (0 , t.dD) is not a function

### Steps to replicate

Install the Winter.Test plugin.

Go to `/backend/winter/test/records/create#secondarytab-formwidgets` and open browser console. You will see an error:

![2023-01-27_092721](https://user-images.githubusercontent.com/61043464/215032382-9ae786fc-dae1-4a19-ab7a-93ee9827e790.jpg)

**Comment by LukeTowers** [comment]
@damsfx @WebVPF I ran into this as well (or something similar), but all I had to do was republish the public folder and clear my browser cache. Does that help you guys as well?

**Comment by xitara** [comment]
I did some testing. After recompiling the assets in dev-develop with `php artisan mix:watch module-backend` I got the error

`"Ein Widget mit dem Klassennamen "formPagefd491768bbe8b2f208d6e5d82758228aViewBagBlocksForm1IconsForm0Icon" wurde nicht mit dem Controller verbunden" on line 606 of htdocs/winter/modules/backend/classes/Controller.php`

when clicking the icon to open the icon-list. I hadn't found any solution at this time but I keep searching when I have time for
The problem is, the javascript can't fetch the iconlist from IconPicker::onLoadIconLibrary()
