### ISSUE TITLE
Image Resizer returns 404 for all images

### ISSUE THREAD

**Issue by jmondragon** [wintercms/winter#837]
### Winter CMS Build

Other (please specify below)

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

When browsing images in the media manager, none of the thumbnails are working.  All requests to the /resizer/ endpoint seem to be failing with a 404 error.  Additionally, if I use the `| resize` on the frontend, images will not load (with 404 error).

This is a brand new install of Winter using `composer create-project wintercms/winter mywinter`.  When I run `php artisan winter:version` I get 1.2.1.

- I'm installing on a brand new server with PHP 8.1 FPM and NGINX 
- I'm serving pages at the root of the domain (not in a subfolder as mentioned in #119).
- I've double/triple checked my nginx config (#635).
- It happens on all image files, not just uppercase extensions (#133) or gif (#87)

Note: I've got a number of sites that I'm migrating from Plesk to CloudPanel, so I've taken the opportunity to do a clean install and upgrade all sites to the latest WinterCMS and PHP.

### Steps to replicate

- Install WinterCMS 1.2.1: `composer create-project wintercms/winter mywinter`
- Upload image in the backend Media Manager
- Highlight the image (thumbnail does not appear)

### Workaround

No workaround for the backend media manager.  I've removed `|resize` from all frontend images.

**Comment by LukeTowers** [comment]
@jmondragon the problem is most likely in your nginx config, if you have a try files directive on asset files (i.e. requests that end with image extensions) and you don't tell nginx to send 404s to Winter then the resizer will never receive a request for a resized image and won't be able to generate it.

Simple test to see if that is the case, go to the URL provided by the `| resize` filter and check the 404 page that's returned. If it's the 404 page from Winter or your theme's 404 page then there's something else going on, but if it's the nginx 404 page then your nginx configuration is at fault.

**Comment by jmondragon** [comment]
Perfect!  This was, in fact the problem.  Although I added all of the recommended configuration settings from here: https://wintercms.com/docs/setup/configuration there was a section at the bottom of the config file that looks like it was trying to cache (and not log) static files:

```
  location ~* ^.+\.(css|js|jpg|jpeg|gif|png|ico|gz|svg|svgz|ttf|otf|woff|woff2|eot|mp4|ogg|ogv|webm|webp|zip|swf|map)$ {
    add_header Access-Control-Allow-Origin "*";
    expires max;
    access_log off;
  }
```

I removed that section and everything works as expected.

Thank you!
