### ISSUE TITLE
When i Update after installing it shows the message please update from composer but when i update from composer it still shows not update message

### ISSUE THREAD

**Issue by amjadniazi48** [wintercms/winter#86]
![composer_update](https://user-images.githubusercontent.com/2420029/115121953-d7f26b00-9fce-11eb-9526-f78cd8e0ec56.png)

**Comment by LukeTowers** [comment]
The marketplace API is being worked on at the moment, should be ready shortly. If you're using composer to manage the core updates though you should set config/cms.php disableCoreUpdates to true so that the backend doesn't try to handle the updates.

Backend updates are the consumer version of Winter, composer managed updates are the developer version. They're mutually exclusive, so don't update the core through the backend if you're already using composer.

**Comment by amjadniazi48** [comment]
Ok, thanks
