### ISSUE TITLE
Project crashes with PHP 8.2

### ISSUE THREAD

**Issue by RoKrypto** [wintercms/winter#865]
### Winter CMS Build

Other (please specify below)

### PHP Version

Other (please specify below)

### Database engine

MySQL/MariaDB

### Plugins installed

Winter.Demo, Winter.Builder

### Issue description

My project runs normally with Winter 1.2.1 and PHP 8.1.

It crashes after switching the PHP version of the Apache Server to 8.2. This is the warning I get:

![image](https://user-images.githubusercontent.com/19767431/225044553-29b671ee-5fdf-4ad1-88f2-a95854f1e4c7.png)

### Steps to replicate

1- Go to settings of the server to change the PHP version from 8.1 to 8.2.
2- Restart the server.
3- Update the browser where the project runs.

**Comment by RoKrypto** [comment]
As of PHP 8.2.0, **php_zip.dll** DLL must be enabled in php.ini. Previously, this extension was built-in. Check the link for further info: https://stackoverflow.com/a/3872578

**Comment by LukeTowers** [comment]
See https://wintercms.com/docs/setup/installation#system-requirements, the ZipArchive PHP Extension is listed as a requirement.

We do check it via composer (https://github.com/wintercms/storm/blob/develop/composer.json#L36), so I'm not sure why that didn't help give you a better error message. Perhaps because it was installed but not enabled?

@bennothommo @jaxwilko do you have any ideas? Should we be putting in a requirements checking script on boot that can check if the required extensions are actually enabled and give better error messages if they aren't?

**Comment by jaxwilko** [comment]
I'm kind of against checking every php module every request, but we could add a cli command to validate the environment perhaps?

**Comment by jaxwilko** [comment]
Maybe we could do it once and cache it forever against a key of the current php version? That way we could perform the check while booting and only do it once

**Comment by bennothommo** [comment]
I think this is a hosting issue, not a Winter issue. @RoKrypto said they switched PHP versions on a pre-existing install - it's up to the hosting provider (or the person managing the hosting) to ensure the correct PHP extensions are enabled in this scenario.

**Comment by bennothommo** [comment]
@RoKrypto please review the enable extensions in whichever interface you used to switch the PHP versions, and ensure that all required extensions are enabled. Feel free to reopen this issue if all the extensions are enabled and you are still getting the error.
