### ISSUE TITLE
Re-add "setTo" method for Illuminate\Mail\Message class

### ISSUE THREAD

**Issue by bennothommo** [wintercms/winter#888]
### Package targeted

Storm Library

### Description

Refs: 
- https://github.com/wintercms/wn-user-plugin/issues/37
- https://github.com/wintercms/wn-user-plugin/pull/38

Re-add some methods that were dropped in recent Laravel versions to maintain BC, perhaps through a Winter CMS extended class. We can perhaps make them deprecated though and encourage people to shift off them.

### Will this change be backwards-compatible?

This will increase backwards compatibility.

**Comment by damanic** [comment]
I just got stung by this issue and landed here.  

Looking into it I do not think the suggestion in this issue is likely to progress. Backwards compatibility would been a consideration for Laravel on v9 DEV. https://laravel.com/docs/9.x/upgrade#symfony-mailer

Plugins should be using the interface provided by wintercms/laravel for mail actions. so that backwards compatibility can be maintained.

The issue for wintercms as I see it relates to the commonly used wm-user-plugin which is no longer compatible with v1.2 installations: https://github.com/wintercms/wn-user-plugin/pull/21

**Comment by bennothommo** [comment]
Looking into this further, I think you're right, @damanic.

I had assumed that `setTo` was still in our docs, but it's not, and the only time this issue has come up has been from our plugin, so we'll just fix it and call it a day.
