### ISSUE TITLE
Firefox going to CMS results the page to have a "Uncaught NS_ERROR_FAILURE: " error.

### ISSUE THREAD

**Issue by qroft** [wintercms/winter#946]
### Winter CMS Build

1.1

### PHP Version

8.1

### Database engine

MySQL/MariaDB

### Issue description

Attention: currently under Firefox 115.0.2. only!

The CMS editor does not pop up and when going to the console i get two errors that some .JS files could not have been loaded.
The error that appears is:

Uncaught NS_ERROR_FAILURE: 
    <anonymous> https://www.xxxxxxx.com/modules/backend/assets/js/winter-min.js?v=1.1.6:1092
    jQuery 2
[winter-min.js:1092](https://www.xxxxxxx.com/modules/backend/assets/js/winter-min.js?v=1.1.6)
Uncaught NS_ERROR_FAILURE: 
    onInitTab https://www.xxxxxxx.com/modules/cms/assets/js/winter.cmspage.js?v1.1.6:227
    jQuery 7
    initTab https://www.xxxxxxx.com/modules/system/assets/ui/storm-min.js?v=1.1.6:4650
    addTab https://www.xxxxxxx.com/modules/system/assets/ui/storm-min.js?v=1.1.6:4662

### Steps to replicate

1. Login to your backend with a Firefox browser.
2. go to CMS
3. Select any page or partial where the editor on the lower right should appear.
4. The code does not appear and the tab containing the title seems disabled / transparent.
![Screenshot from 2023-07-14 16-02-56](https://github.com/wintercms/winter/assets/14896725/f25d69a7-8766-4a53-817c-5958a29b2004)

### Workaround

Use Google Chrome or Chromium :)

**Comment by bennothommo** [comment]
`NS_ERROR_FAILURE` is almost certainly a failure at the hosting or computer level - usually it's thrown if there's a network issue or if there's a content policy in place at the host. I doubt this will be caused by Winter directly, unfortunately. If it reoccurs, please take a screenshot of the developer tools console showing the full error - that might be able to give us some more context to work with.
